### ISSUE TITLE
SherlockFragmentActivity

### ISSUE THREAD

**Issue by jblernout** [Prototik/HoloEverywhere#127]
The SActivity doesn't work SFragment, it crashes on ICS with the following error :

Caused by: java.lang.ClassCastException: ....Fragment cannot be cast to android.app.Fragment

maybe a SFragmentActitvity would do the trick

**Comment by tmurakami** [comment]
I had this same issue.
By using the "fragment" tag in a layout.xml, ClassCastException occurs.

Reason:
HoloEverywhere has a custom LayoutInflater.
However, because it overrides Activity#getLayoutInflater, Factory is not set.
(Normally, Factory is set at FragmentActivity#onCreate.)

Workaround:
Add the following code to your activity.

```
@Override
public com.WazaBe.HoloEverywhere.LayoutInflater getLayoutInflater() {
  return (com.WazaBe.HoloEverywhere.LayoutInflater)getWindow().getLayoutInflater();
}
```

**Comment by jblernout** [comment]
Thanks for the tip!

**Comment by Prototik** [comment]
... What? Window layout inflater (just PhoneLayoutInflater from internal android package) cannot be cast to HoloEverywhere.LayoutInflater, never. Try getLayoutInflater().setFactory(this) before calling super.onCreate in activity.

**Comment by tmurakami** [comment]
getSystemService() has been overridden by com.WazaBe.HoloEverywhere.app.Activity.
Therefore, I think getWindow().getLayoutInflater() returns HoloEverywhere's LayoutInflater.

The cause of this issue is that Factory is not set to LayoutInflater returned by getSystemServices().
Therefore, I used the above code.
With that code, Factory is set at FragmentActivity#onCreate.

I think also this issue is solved using the following code.

```
@Override
public Object getSystemService(String name) {
  Object service = super.getSystemService(name);
  if (service instanceof com.WazaBe.HoloEverywhere.LayoutInflater) {
    com.WazaBe.HoloEverywhere.LayoutInflater li = (com.WazaBe.HoloEverywhere.LayoutInflater)service;
    if (li.getFactory() == null) {
      li.setFactory(this);
    }
  }
  return service;
}
```

**Comment by Prototik** [comment]
Test it with new version

**Comment by tmurakami** [comment]
With HoloEverywhere 1.3, my project works fine!
Thanks for your good work!

**Comment by SebaSOFT** [comment]
Still think we need a SFragmentActivity, The two pane example in Eclipse quickly gets this Exception when you start adding a  little complexity to it... 

The inflater stuff tries to cast my fragmentactivity as com.WazaBe.HoloEverywhere.app.Activity at some point inside Android's code...

Confirmed in Android 4.1.2 still getting

[code]
10-31 19:35:36.162: E/AndroidRuntime(691): Caused by: java.lang.ClassCastException: com.example.MyFragmentActivity cannot be cast to com.WazaBe.HoloEverywhere.app.Activity
10-31 19:35:36.162: E/AndroidRuntime(691):  at com.WazaBe.HoloEverywhere.app.Fragment.onInflate(Fragment.java:138)
10-31 19:35:36.162: E/AndroidRuntime(691):  at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:271)
10-31 19:35:36.162: E/AndroidRuntime(691):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:676)
10-31 19:35:36.162: E/AndroidRuntime(691):  ... 22 more
[/code]

**Comment by Prototik** [comment]
Use SActivity, man.

**Comment by SebaSOFT** [comment]
SActivity won't load a layout with a &lt; fragment &gt; tag

**Comment by Prototik** [comment]
Yes, it's bug. I know.

**Comment by ElArZ** [comment]
Is there a workaround to this last issue?

I'm experiencing the same thing using SherlockFragmentActivity.

**Comment by Prototik** [comment]
@ElArZ already fixed in dev version

**Comment by ElArZ** [comment]
Thank you for the quick fix.

**Comment by ElArZ** [comment]
Still getting the "can't cast to Activity" error when using SherlockFragmentActivity.

And using the SActivity, it still can't find fragment class.
(Using the latest dev version: 1.3.4-SNAPSHOT)

**Comment by SebaSOFT** [comment]
I had to fall back to Sherlock only activities and fragments

**Comment by felipecsl** [comment]
I'm still having this issue, trying to inflate a HoloEverywhere `Activity` with `<fragment>` elements which are HoloEverywhere `Fragment`. I get a ClassCastException trying to cast them to `android.app.fragment`.
Gave up so far. Using latest HoloEverywhere 1.5 with android support v4. Ideas?
