### ISSUE TITLE
FontLoader - StackOverflow

### ISSUE THREAD

**Issue by r-gurzkowski** [Prototik/HoloEverywhere#667]
When loading a font, StackOverflow error can be thrown, when any type of exception is thrown during creating font object from file. 

Affected function is RawFont.loadTypeface(File file, boolean allowFileReusage). allowFileReusage is always set to true, however when something goes wrong it is set to false recursively causing infinite recursion. 

This bug was produced using robolectric with invalid cache font cache support. It was already fixed: https://github.com/robolectric/robolectric/pull/692. However it shows that exception handling mechanism in this function is not implemented correctly.

Thanks for your support!

**Comment by BraisGabin** [comment]
HE version? I think this bug was solved.

**Comment by r-gurzkowski** [comment]
1.6.8. I downloaded code from master and it is still broken. When Typeface.createFromFile throws an exception, allowFileReusage is set to false, which is causing StackOverflow. I think it should return null, when you don't want to retry or continue recursion with allowFileReusage - true.

``` java
 private Typeface loadTypeface(File file, boolean allowFileReusage) {
            if (file.exists() && allowFileReusage) {
                try {
                    Typeface typeface = Typeface.createFromFile(file);
                    if (typeface == null) {
                        throw new NullPointerException();
                    }
                    return typeface;
                } catch (Exception e) {
                    return loadTypeface(false);
                }
            } else {
                try {
                    InputStream is = getContext().getResources().openRawResource(mRawResourceId);
                    OutputStream os = new FileOutputStream(file);
                    byte[] buffer = new byte[1024];
                    int c;
                    while ((c = is.read(buffer)) > 0) {
                        os.write(buffer, 0, c);
                    }
                    os.flush();
                    os.close();
                    is.close();
                    return loadTypeface(file, allowFileReusage);
                } catch (Exception e) {
                    return null;
                }
            }
        }
```

**Comment by Prototik** [comment]
No, stop.
In original code when any error occurred (and allowFileReusage = true) invoking loadTypeface again with allowFileReusage = false. If allowFileReusage already is false or it's second call after allowFileReusage = true then just try to unpack typeface and load it. I don't see any recursion in this algorithm.

**Comment by r-gurzkowski** [comment]
It does not stop, when font cannot be loaded:

j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Z)Landroid/graphics/Typeface;+38
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+33
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Ljava/io/File;Z)Landroid/graphics/Typeface;+111
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface(Z)Landroid/graphics/Typeface;+38
j  org.holoeverywhere.FontLoader$RawFont.loadTypeface()Landroid/graphics/Typeface;+6
j  org.holoeverywhere.FontLoader$Font.getTypeface(Ljava/lang/String;I)Landroid/graphics/Typeface;+9

**Comment by mjurkus** [comment]
Same here with `1.6.8` when while running test with Gradle.

```
Caused by: java.lang.StackOverflowError
    at sun.nio.cs.UTF_8.updatePositions(UTF_8.java:58)
    at sun.nio.cs.UTF_8$Encoder.encodeArrayLoop(UTF_8.java:392)
    at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:447)
    at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:544)
    at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:240)
    at java.lang.StringCoding.encode(StringCoding.java:272)
    at java.lang.String.getBytes(String.java:946)
    at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
    at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:228)
    at java.io.File.exists(File.java:733)
    at org.holoeverywhere.FontLoader$RawFont.loadTypeface(FontLoader.java:248)
    at org.holoeverywhere.FontLoader$RawFont.loadTypeface(FontLoader.java:270)
    at org.holoeverywhere.FontLoader$RawFont.loadTypeface(FontLoader.java:270)
    at org.holoeverywhere.FontLoader$RawFont.loadTypeface(FontLoader.java:270)
    at org.holoeverywhere.FontLoader$RawFont.loadTypeface(FontLoader.java:270)
    at org.holoeverywhere.FontLoader$RawFont.loadTypeface(FontLoader.java:270)
        ...
```

**Comment by BraisGabin** [comment]
`v1.6.8` have this error. There was a recursion loop when `allowFileReusage = false` because never again was set to `true`. But this issue is fixed on `master`.

**Comment by mjurkus** [comment]
With master we had way more problems, so we're sticking to this version. At least for now.

**Comment by Prototik** [comment]
/Then/ backport patch to 1.6.8 and don't disturb me anymore. I cannot support more than one version of library.
