### ISSUE TITLE
ProgressDIalog in Android 4.1.1

### ISSUE THREAD

**Issue by M1cha** [Prototik/HoloEverywhere#71]
I create a Dialog with this code:

``` java
progressDialog = ProgressDialog.show(this, getString(R.string._please_wait), getString(R.string._loading_feeds), true, false);
```

EDIT: If I change my target-Platform from "android-14" to "android-15", I don't get an error, but the description-text of the Progress-dialog is missing.

I'm testing in 2.2 and 4.1.1. In 4.1.1 it works just fine, but in 2.2 I get an Resource$NotFoundException:

``` java
E/AndroidRuntime( 6749): FATAL EXCEPTION: main
E/AndroidRuntime( 6749): java.lang.RuntimeException: Unable to start activity ComponentInfo{MY_ACTIVITY}: android.content.res.Resources$NotFoundException: Resource ID #0x1030298                                                                           
E/AndroidRuntime( 6749):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)                                                      
E/AndroidRuntime( 6749):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2212)                                                       
E/AndroidRuntime( 6749):  at android.app.ActivityThread.access$600(ActivityThread.java:144)                                                                  
E/AndroidRuntime( 6749):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)                                                            
E/AndroidRuntime( 6749):  at android.os.Handler.dispatchMessage(Handler.java:99)                                                                             
E/AndroidRuntime( 6749):  at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 6749):  at android.app.ActivityThread.main(ActivityThread.java:4965)
E/AndroidRuntime( 6749):  at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6749):  at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 6749):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 6749):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
E/AndroidRuntime( 6749):  at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 6749): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x1030298
E/AndroidRuntime( 6749):  at android.content.res.Resources.getValue(Resources.java:1013)
E/AndroidRuntime( 6749):  at android.content.res.Resources.loadXmlResourceParser(Resources.java:2127)
E/AndroidRuntime( 6749):  at android.content.res.Resources.getLayout(Resources.java:852)
E/AndroidRuntime( 6749):  at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
E/AndroidRuntime( 6749):  at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
E/AndroidRuntime( 6749):  at android.view.View.inflate(View.java:16119)
E/AndroidRuntime( 6749):  at com.WazaBe.HoloEverywhere.AlertDialog.setView(AlertDialog.java:766)
E/AndroidRuntime( 6749):  at com.WazaBe.HoloEverywhere.AlertDialog.setView(AlertDialog.java:761)
E/AndroidRuntime( 6749):  at com.WazaBe.HoloEverywhere.ProgressDialog.onCreate(ProgressDialog.java:179)
E/AndroidRuntime( 6749):  at android.app.Dialog.dispatchOnCreate(Dialog.java:351)
E/AndroidRuntime( 6749):  at android.app.Dialog.show(Dialog.java:256)
E/AndroidRuntime( 6749):  at com.WazaBe.HoloEverywhere.ProgressDialog.show(ProgressDialog.java:44)
E/AndroidRuntime( 6749):  at com.WazaBe.HoloEverywhere.ProgressDialog.show(ProgressDialog.java:32)
E/AndroidRuntime( 6749):  at MY_ACTIVITY
```

**Comment by Prototik** [comment]
Fixed in 1.2.1

**Comment by M1cha** [comment]
Sorry, but no it's not fixed. With 1.2.1 every dialog seems to be completely broken. No Dialog, No Links, no ProgressDialog.

``` java
: Caused by: android.view.InflateException: Binary XML file line #89: Error inflating class <unknown>                                            
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.createView(LayoutInflater.java:613)                                                                      
E/AndroidRuntime( 7473):        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)                                       
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)                                                                    
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)                                                               
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)                                                                        
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)                                                                        
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)                                                                         
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)                                                                         
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)                                                                         
E/AndroidRuntime( 7473):        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:256)                                                    
E/AndroidRuntime( 7473):        at com.WazaBe.HoloEverywhere.internal.AlertController.installContent(AlertController.java:451)                                          
E/AndroidRuntime( 7473):        at com.WazaBe.HoloEverywhere.AlertDialog.onCreate(AlertDialog.java:348)                                                                 
E/AndroidRuntime( 7473):        at com.WazaBe.HoloEverywhere.ProgressDialog.onCreate(ProgressDialog.java:211)
```

**Comment by Prototik** [comment]
E/AndroidRuntime( 7473):        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)                                                                         

It's not correct, shoud use com.WazaBe.HoloEverywhere.LayoutInflater.

You have latest source?

**Comment by M1cha** [comment]
Ah sorry for that. Didn't have the last two commits.
I was too fast with pulling your new code :D Good work BTW :)
